export const DURATION_SHELF_DELETION_MILLISEC = 8000
export const DURATION_MULTIPLE_CARDS_DELETION_MILLISEC = 6000
export const DURATION_SEC = 0.5
export const DURATION_MILLISEC = 500
export const DURATION_SHELF_COLLAPSING_SEC = 0.3
export const DURATION_DELAY_SWITCH_MODE_SHELF_TEMPLATE_SETTINGS = 1