export const idTimeSetterHidden = 'timeSetterHidden'
export const idDropDownLocalTemplateHidden = 'dropDownLocalTemplateHidden'
export const idCupboardShelfList = 'cupboardShelfList'
export const idBoxesBlockCommonWrapper = 'boxesBlockCommonWrapper'
export const dataAttrTimeSetterSingle = 'time-setter-single-setter-component'